# Generated by Django 4.2.7 on 2023-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='username',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
