# Generated by Django 4.2.7 on 2023-11-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0003_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.CharField(max_length=10),
        ),
    ]
