# Generated by Django 4.2.7 on 2023-11-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0005_alter_prodotto_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManager.prodotto')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManager.utente')),
            ],
        ),
    ]
