# Generated by Django 4.2.7 on 2023-11-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0006_carrello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrello',
            name='prodotto',
        ),
        migrations.RemoveField(
            model_name='carrello',
            name='quantita',
        ),
        migrations.AlterField(
            model_name='carrello',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StoreManager.utente'),
        ),
        migrations.CreateModel(
            name='CarrelloProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1)),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManager.carrello')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManager.prodotto')),
            ],
        ),
        migrations.AddField(
            model_name='carrello',
            name='prodotti',
            field=models.ManyToManyField(through='StoreManager.CarrelloProdotto', to='StoreManager.prodotto'),
        ),
    ]
