# Generated by Django 4.2.7 on 2023-12-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0007_remove_carrello_prodotto_remove_carrello_quantita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('importo_totale', models.FloatField(default=0.0)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManager.utente')),
            ],
        ),
        migrations.AddField(
            model_name='carrelloprodotto',
            name='ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreManager.ordine'),
        ),
    ]
