# Generated by Django 4.2.7 on 2023-12-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0009_ordine_prodotti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='prodotti',
        ),
    ]
